// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateOrderInput struct {
	Message string `json:"message"`
}

type CreatePatientInput struct {
	Name string `json:"name"`
}

type Mutation struct {
}

type Order struct {
	ID      string  `json:"id"`
	Message *string `json:"message,omitempty"`
}

type Patient struct {
	ID      string  `json:"id"`
	Name    string  `json:"name"`
	OrderID *string `json:"orderId,omitempty"`
}

type Query struct {
}

type UpdateOrderInput struct {
	ID      string `json:"id"`
	Message string `json:"message"`
}

type UpdatePatientInput struct {
	ID      string  `json:"id"`
	Name    *string `json:"name,omitempty"`
	OrderID *string `json:"orderId,omitempty"`
}
