// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewOrder struct {
	Message string `json:"message"`
}

type NewPatient struct {
	Name string `json:"name"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Order struct {
	ID      string  `json:"id"`
	Message *string `json:"message,omitempty"`
}

type Patient struct {
	ID      string  `json:"id"`
	Name    string  `json:"name"`
	OrderID *string `json:"orderId,omitempty"`
}

type Query struct {
}

type UpdateOrder struct {
	Message string `json:"message"`
}

type UpdatePatient struct {
	Name    string  `json:"name"`
	OrderID *string `json:"orderId,omitempty"`
}
